[project]
name = "procrastist"
version = "0.1.0"
description = "Automatic rescheduling of todoist tasks"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.2",
    "todoist-api-python>=3.1.0",
    "tzdata>=2025.2",
]
